CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  # Write your MySQL query statement below.
  DECLARE DISTINCT_ROW_NUM INT;
  DECLARE OFFSET_NUM INT;

  SET DISTINCT_ROW_NUM = (SELECT COUNT(DISTINCT(Salary)) FROM Employee);
  SET OFFSET_NUM = N - 1;

  IF N > DISTINCT_ROW_NUM THEN RETURN NULL;
  ELSE RETURN (SELECT DISTINCT(Salary) FROM Employee ORDER BY Salary DESC LIMIT 1 OFFSET OFFSET_NUM);
  END IF;
END